Updated link script

diff --git a/link b/link
--- a/link
+++ b/link
@@ -51,6 +51,25 @@ pickHost() {
 
     exit 0
   fi
+  if [ $host = "sudo" ]; then
+    sudo mkdir -p $STRIPPED_TARGET
+    if [ ! -d "$SCRIPT_PATH/sudo" ]; then
+      echo "Error: The files for this configuration are missing"
+      exit 1
+    fi
+    sudo \cp -rf $SCRIPT_PATH/sudo/$PROGRAM_NAME/. $STRIPPED_TARGET
+
+    if [ $? -eq 0 ]; then
+      echo "Successfully copied files for the $PROGRAM_NAME package"
+      echo "    - The configuration is $host"
+      echo "    - The target is $PROGRAM_TARGET"
+    else
+      echo "Error: Failed to copy files in configuration $host"
+      exit 1
+    fi
+
+    exit 0
+  fi
   if [ $host = "laptop" ]; then
     mkdir -p $PROGRAM_TARGET
     if [ ! -d "$SCRIPT_PATH/laptop" ]; then
